// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import {UltraVerifier as RevealVerifier} from "../verifiers-generated/RevealVerifier.sol";

/// @notice verify-e2e artifact.
/// Consumes a real UltraPlonk proof generated by prover/prove-reveal.mjs and
/// asserts:
///   1. the real proof is accepted by the on-chain verifier
///   2. a tampered public input (swapping a revealed card) is rejected
///      by the verifier itself (not by a Solidity require downstream)
///
/// This is the live proof of the ZK pipeline. The fixture is regenerated
/// via `node prover/prove-reveal.mjs --out prover/fixture.json`.
contract RevealVerifierTest is Test {
    RevealVerifier verifier;

    bytes proof;
    bytes32[] publicInputs;

    function setUp() public {
        verifier = new RevealVerifier();

        // Fixture loaded via FFI-free JSON read (forge cheatcode).
        string memory root = vm.projectRoot();
        string memory path = string.concat(root, "/../prover/fixture.json");
        string memory json = vm.readFile(path);

        proof = vm.parseJsonBytes(json, ".proofHex");
        bytes32[] memory pubs = vm.parseJsonBytes32Array(json, ".publicInputs");
        publicInputs = pubs;
    }

    function test_real_proof_accepted() public {
        bool ok = verifier.verify(proof, publicInputs);
        assertTrue(ok, "RevealVerifier rejected a valid proof");
    }

    function test_tampered_card_rejected() public {
        // Swap revealed_cards[0] from 7 (0x07) to an arbitrary other card (0x08).
        // The circuit commitment binds card|nonce, so the pedersen check fails
        // and the verifier returns false WITHOUT the transaction reaching any
        // Solidity-level require. This is the value prop of ZK: tampering is
        // caught at the cryptographic layer.
        bytes32[] memory tampered = new bytes32[](publicInputs.length);
        for (uint256 i = 0; i < publicInputs.length; i++) {
            tampered[i] = publicInputs[i];
        }
        tampered[2] = bytes32(uint256(8));

        // UltraVerifier reverts on a failed pairing (rather than returning false).
        // Either outcome (false return or revert) counts as rejection.
        (bool success, bytes memory ret) = address(verifier).staticcall(
            abi.encodeWithSelector(verifier.verify.selector, proof, tampered)
        );

        if (success) {
            bool accepted = abi.decode(ret, (bool));
            assertFalse(accepted, "RevealVerifier accepted a tampered public input");
        }
        // success == false means verifier reverted: also rejection. OK.
    }

    function test_tampered_commitment_rejected() public {
        bytes32[] memory tampered = new bytes32[](publicInputs.length);
        for (uint256 i = 0; i < publicInputs.length; i++) {
            tampered[i] = publicInputs[i];
        }
        // Flip a bit in the first commitment.
        tampered[0] = bytes32(uint256(publicInputs[0]) ^ uint256(1));

        (bool success, bytes memory ret) = address(verifier).staticcall(
            abi.encodeWithSelector(verifier.verify.selector, proof, tampered)
        );

        if (success) {
            bool accepted = abi.decode(ret, (bool));
            assertFalse(accepted, "RevealVerifier accepted a tampered commitment");
        }
    }
}
